// Problem: id is generated by chrome.tabs and is only unique to 1 instance. need to have a unique id for the tabs that holds across sessions.
export interface Tab {
  id: number;
  currentUrl: string;
  history: string[];
  title: string;
  timestamp: number;
}

export interface Todo {
  id: number;
  text: string;
  completed: boolean;
  active?: boolean;
  tabs?: Tab[];
  windowId?: number;
}
